language: node_js

node_js:
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"

matrix:
  include:
    - node_js: "node"
      name: "Node.js: nightly"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - node_js: "node"
      name: "Node.js: canary"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

  allow_failures:
    - name: "Node.js: nightly"
    - name: "Node.js: canary"

sudo: false

cache:
  directories:
    - node_modules
    - ~/.npm

git:
  depth: 3

install:
  - npm install --ignore-scripts

script:
  - npm run test:coverage

after_success:
  - npm run coverage
